config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :rails
  resources :passengers
  resources :trips
  resources :drivers, except: [:destroy]
  resources :buses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/rail.rb
class Rail < ApplicationRecord
  belongs_to :passenger
  belongs_to :trip
end

app/controllers/rails_controller.rb
class RailsController < ApplicationController
  before_action :set_rail, only: %i[ show edit update destroy ]

  # GET /rails or /rails.json
  def index
    @rails = Rail.all
  end

  # GET /rails/1 or /rails/1.json
  def show
  end

  # GET /rails/new
  def new
    @rail = Rail.new
  end

  # GET /rails/1/edit
  def edit
  end

  # POST /rails or /rails.json
  def create
    @rail = Rail.new(rail_params)

    respond_to do |format|
      if @rail.save
        format.html { redirect_to rail_url(@rail), notice: "Rail was successfully created." }
        format.json { render :show, status: :created, location: @rail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rails/1 or /rails/1.json
  def update
    respond_to do |format|
      if @rail.update(rail_params)
        format.html { redirect_to rail_url(@rail), notice: "Rail was successfully updated." }
        format.json { render :show, status: :ok, location: @rail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rails/1 or /rails/1.json
  def destroy
    @rail.destroy!

    respond_to do |format|
      format.html { redirect_to rails_url, notice: "Rail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rail
      @rail = Rail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rail_params
      params.require(:rail).permit(:Reservation, :passenger_id, :trip_id)
    end
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/views/rails/_form.html.erb
<%= form_with(model: rail) do |form| %>
  <% if rail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rail.errors.count, "error") %> prohibited this rail from being saved:</h2>

      <ul>
        <% rail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Reservation, style: "display: block" %>
    <%= form.text_field :Reservation %>
  </div>

  <div>
    <%= form.label :passenger_id, style: "display: block" %>
    <%= form.text_field :passenger_id %>
  </div>

  <div>
    <%= form.label :trip_id, style: "display: block" %>
    <%= form.text_field :trip_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rails/_rail.html.erb
<div id="<%= dom_id rail %>">
  <p>
    <strong>Reservation:</strong>
    <%= rail.Reservation %>
  </p>

  <p>
    <strong>Passenger:</strong>
    <%= rail.passenger_id %>
  </p>

  <p>
    <strong>Trip:</strong>
    <%= rail.trip_id %>
  </p>

</div>

app/views/rails/edit.html.erb
<h1>Editing rail</h1>

<%= render "form", rail: @rail %>

<br>

<div>
  <%= link_to "Show this rail", @rail %> |
  <%= link_to "Back to rails", rails_path %>
</div>

app/views/rails/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rails</h1>

<div id="rails">
  <% @rails.each do |rail| %>
    <%= render rail %>
    <p>
      <%= link_to "Show this rail", rail %>
    </p>
  <% end %>
</div>

<%= link_to "New rail", new_rail_path %>

app/views/rails/new.html.erb
<h1>New rail</h1>

<%= render "form", rail: @rail %>

<br>

<div>
  <%= link_to "Back to rails", rails_path %>
</div>

app/views/rails/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rail %>

<div>
  <%= link_to "Edit this rail", edit_rail_path(@rail) %> |
  <%= link_to "Back to rails", rails_path %>

  <%= button_to "Destroy this rail", @rail, method: :delete %>
</div>